version: "3"

tasks:
  install:
    desc: Install all necessary dependencies
    cmds:
      - uv sync
      - task: onedl:clone
      - task: onedl:install

  onedl:clone:
    desc: Clone the onedl repositories
    cmds:
      - git clone https://github.com/vbti-development/onedl-mmengine
      - git clone https://github.com/vbti-development/onedl-mmcv
      - git clone https://github.com/vbti-development/onedl-mmpretrain
      - git clone https://github.com/vbti-development/onedl-mmdetection
      - git clone https://github.com/vbti-development/onedl-mmsegmentation
    dir: repos
  
  onedl:install:
    desc: Install the mmdetection library
    cmds:
      #- mim uninstall -y onedl-mmengine onedl-mmcv onedl-mmpretrain onedl-mmdetection onedl-mmsegmentation
      #- mim install -U onedl-mmengine onedl-mmcv onedl-mmpretrain onedl-mmdetection onedl-mmsegmentation
      #- task: mmengine:compile
      - task: mmcv:compile
    dir: .

  mmengine:compile:
    desc: Compile mmengine with CUDA support (see https://onedl-mmengine.readthedocs.io/en/latest/get_started/build.html)
    cmds:
      - uv pip install -e . -v
    dir: repos/onedl-mmengine

  mmcv:compile:
    desc: Compile mmcv with CUDA support (see https://onedl-mmcv.readthedocs.io/en/latest/get_started/build.html)
    cmds:
      - uv pip install -e . -v
    dir: repos/onedl-mmcv

  run-tests:
    desc: Run tests
    cmds:
      - pytest tests/
    dir: .
  
  
