version: "3"

tasks:
  setup:
    desc: Setup project
    cmds:
      - task: venv
      - task: download-mm
      - task: sync

  venv:
    desc: Create virtual environment
    cmds:
      - uv venv --python 3.12

  sync:
    desc: Install all necessary dependencies
    cmds:
      - uv sync
      - task: install-mm

  download-mmd:
    desc: Download the mmdetection repository
    cmds:
      - git clone https://github.com/open-mmlab/mmpretrain
      - git clone https://github.com/open-mmlab/mmdetection.git
      - git clone https://github.com/open-mmlab/mmsegmentation
    dir: .
  
  install-mm:
    desc: Install the mmdetection library
    cmds:
      - mim uninstall -y onedl-mmengine onedl-mmcv onedl-mmpretrain onedl-mmdetection onedl-mmsegmentation
      - mim install -U onedl-mmengine onedl-mmcv onedl-mmpretrain onedl-mmdetection onedl-mmsegmentation
    dir: .

  onedl:clone:
    desc: Clone the onedl repositories
    cmds:
      - git clone https://github.com/vbti-development/onedl-mmengine
      - git clone https://github.com/vbti-development/onedl-mmcv
      - git clone https://github.com/vbti-development/onedl-mmpretrain
      - git clone https://github.com/vbti-development/onedl-mmdetection
      - git clone https://github.com/vbti-development/onedl-mmsegmentation
    dir: repos

  mmcv:compile:
    desc: Compile mmcv with CUDA support (see https://onedl-mmcv.readthedocs.io/en/latest/get_started/build.html)
    cmds:
      - uv pip install -e . -v
    dir: repos/onedl-mmcv

  run-tests:
    desc: Run tests
    cmds:
      - pytest tests/
    dir: .
  
  
